### PR TITLE
update regexp for duration & interval check

### LINKED ISSUE #36: False positive on interval syntax
`interval = 5` should not rise the `The interval is invalid (try a number of minutes)` error. The regexp needs to be verified.

Probably same bug with `duration`.

### PR DESCRIPTION
**Pull request by nlehuby**
Fix #36

### CODE REVIEW

**Comment by frodrigo** [comment]
May be try to add assert to validate the regex?

**Comment by nlehuby** [comment]
Good idea, it's done.

Do you know how I can test it ?

**Comment by frodrigo** [comment]
I tested it with Osmose

```
Traceback (most recent call last):
  File "/home/fred/frodrigo-osmose-backend/plugins/Josm_transport.py", line 560, in test
    self.check_err(n.relation(data, {u'interval': u'00:70:00'}, []), expected={'class': 9014021, 'subclass': 726428353})
  File "/home/fred/frodrigo-osmose-backend/plugins/Plugin.py", line 148, in check_err
    assert errors, log
nose.proxy.AssertionError: Valid errors expected
```

**Comment by frodrigo** [comment]
assertMatch and assertNoMatch: You can give there examples, which should (assertMatch) or should not (assertNoMatch) match the used selector. So this is a test if the selector works correct for the given example. Normally this is only usefull for more complex selectors and less for simple key-value selectors. The tests are executed in the context of unit tests and on ​jenkins/job/JOSM. They are also executed for local validator files if the advanced option validator.check_assert_local_rules is set to "true" in the advanced preferences (see #10206). If you enabled this option and the test fails, you will get a message in the console output which can look like: WARNING: Expecting test '...' to match way ... or ...to not match.... 


https://josm.openstreetmap.de/wiki/Help/Validator/MapCSSTagChecker

**Comment by nlehuby** [comment]
Thanks for these valuable info.
I've updated the doc, the rules and the tests accordingly.

**Pull request merged**
