### PR TITLE
pull translation strings

### PR DESCRIPTION
**Pull request by nlehuby**

### CODE REVIEW

**Comment by nlehuby** [comment]
@frodrigo can you please also update Osmose frontend with the translations ?
Most of the 9014 Osmose issues are still in English only :(

**Comment by frodrigo** [comment]
I don't know how it works in Osmose. Maybe we never setup it.
@jocelynj

**Comment by nlehuby** [comment]
How can I help with this @frodrigo @jocelynj ? It's too bad that we don't have the translations in Osmose :cry:

**Comment by jocelynj** [comment]
Where can we find these translations?

There are two parts to configure in osmose-backend:
1) downloading .po files in https://github.com/osm-fr/osmose-backend/blob/master/po/Makefile
2) adding path to use these .po files in https://github.com/osm-fr/osmose-backend/blob/master/modules/OsmoseTranslation.py#L32

**Comment by nlehuby** [comment]
the translations are here : https://www.transifex.com/openstreetmap-france/osmose/transport_mapcss/

**Comment by nlehuby** [comment]
thanks @jocelynj :heart:

**Pull request merged**
