### PR TITLE
I18n tofix

### PR DESCRIPTION
**Pull request by nlehuby**
I've reverted the merge of the i18n PR.

Here is what needs to be fixed:

- [x]  build zip where translations are ok (when I use JOSM in French, I should see the errors in French)
- [ ]  all the errors listed should appear (for now, the ones with a -osmose-`item-class-level` or a `group` does not work). Removing the group is a valid fix for now (for JOSM at least)
- [x]  change metadata link to https

### CODE REVIEW

**Comment by frodrigo** [comment]
The `-osmose*` declarations are still experimental, and not part of this.

The group problem should be fixed.

**Comment by nlehuby** [comment]
The translations does not seem ok with this version.
image

Still, it is the same structure as the zip we released :thinking:

**Comment by prhod** [comment]
I made some checks with @nlehuby , and the translation into french is not available in JOSM because the `en.lang` file is not in the zip file. 
Is there a reason behind the removing of this file ?

**Comment by nlehuby** [comment]
Assuming JOSM is already in French (dunno how to change the language):
* Préférences
* Validateur de données
* Onglet Règles du vérificateur d'attributs
*  Bouton +
* add the path to the zip file

Beware that once the translation strings are loaded, they are used anyhow, even if you have disabled the file which adds them. You should restart JOSM between each zip test to make sure it is ok.

**Comment by nlehuby** [comment]
I don't know why, but the en.lang seems to be generated each time the i18n.pl script is used. It only contains 6 translated strings because the last po only have 6 strings (zh_CN)...

That's quite ugly, but I've updated the makefile to launch the i18n.pl script again on the French po at the end of the process and it looks ok.

Feedback welcomed on this last zip, and on a better way to deal with the process.

**Comment by frodrigo** [comment]
@nlehuby Your change still produce invalid lang file for other language.
Now we generate all lang file at once and it automatically produce the en.lang.
By the way, the result in JOSM is again English only... I still don't know why.

I also move the mapcss file to zip root directory as requested by @stoecker on #11.

**Comment by josmmirror** [comment]
Is there a test file for me?

**Comment by stoecker** [comment]
I sthere a test file for me?

**Comment by frodrigo** [comment]
https://github.com/Jungle-Bus/transport_mapcss/raw/i18n_tofix/transport.validator.zip

**Comment by stoecker** [comment]
Works here. Caching issue?

**Comment by frodrigo** [comment]
I'm on JOSM 13500 and validation result are in English and not translated.

**Comment by stoecker** [comment]
See above: Are you sure you are using the newest file? Clear the JOSM cache to be sure or download the file and add a local URL.

**Comment by nlehuby** [comment]
I think you need to update josm to the last stable release, v13500 does not have i18n on rules.

**Comment by frodrigo** [comment]
Ok, works for me too.

**Comment by nlehuby** [comment]
There is still an issue:
image

The errors are in French (which is good :+1:), but they are still shuffled:
"Est-ce un arrêt de bus ou une gare routière ?" (is it a bus stop or a bus station) appears when a route_master relation is missing
"Est-ce un arrêt de bus ? ajouter highway=bus_stop" is not supposed to be the label of a group and appears on tram stop without public_transport tag.
etc

**Comment by frodrigo** [comment]
Nevertheless the content on the zip file look ok for me:
```
$ perl -CDSL ../po/langinfo.pl en.lang fr.lang
   1    32 Check if the note can be deleted
   2    21 Check the network tag
   3    22 Check the operator tag
   4    34 Is it a bus stop or a bus station?
   5    48 Is this a bus stop? add the tag highway=bus_stop
   6    56 Missing from/to tag on a public_transport route relation
   7    45 Missing legacy tag on a public transport stop
   8    50 Missing network tag on a public_transport relation
   9    51 Missing operator tag on a public_transport relation
  10    55 Missing public_transport tag on a public transport stop
  11    73 Missing public_transport:version tag on a public_transport route relation
  12    62 Missing ref tag for line number on a public_transport relation
  13    65 Missing transportation mode, add a tag route = bus/coach/tram/etc
  14    61 Missing transportation mode, change tag route to route_master
  15    77 Specify if it is a stop (platform) or a location on the rails (stop_position)
  16    76 Specify if it is a stop (platform) or a location on the road (stop_position)
  17    17 Stop without name
  18    75 The legacy tag is missing, add the tag highway=bus_stop / railway=tram_stop
  19    81 The line variant does not belong to any line, add it to the route_master relation
  20    65 The network should be on the transport lines and not on the stops
  21    66 The operator should be on the transport lines and not on the stops
  22    62 The stop is not served by any line, add it to a route relation
  23    39 The stops may not be in the right order
  24    41 Uncompromising validation of transit data
multi:
Status: Missing 0/0 - 24,0,0,0,0
   1    42 Vérifier si la note peut être supprimée
   2    36 Vérifier le réseau sur tag network
   3    43 Vérifier l''opérateur sur le tag operator
   4    47 Est-ce un arrêt de bus ou une gare routière ?
   5    57 Est-ce un arrêt de bus ? ajouter le tag highway=bus_stop
   6    62 L''origine/destination est manquante, ajouter les tags from/to
   7    50 Le tag de transport public historique est manquant
   8    47 Le réseau est manquant, ajouter un tag network
   9    51 L''opérateur est manquant, ajouter un tag operator
  10    47 Il manque le tag public_transport sur un arrêt
  11    76 La version de schéma est manquante, ajouter un tag public_transport:version
  12    52 Le numéro de ligne est manquant, ajouter un tag ref
  13    63 Le mode est manquant, ajouter un tag route = bus/coach/tram/etc
  14    62 Le mode est manquant, transformer le tag route en route_master
  15    98 Préciser s''il s''agit d''un arrêt (platform) ou d''un emplacement sur les rails (stop_position)
  16    97 Préciser s''il s''agit d''un arrêt (platform) ou d''un emplacement sur la route (stop_position)
  17    25 L''arrêt n''a pas de nom
  18    81 Le tag historique est manquant, ajouter le tag highway=bus_stop/railway=tram_stop
  19    91 La variante de ligne n''appartient à aucune ligne (l''ajouter à la relation route_master)
  20    82 Le réseau devrait être porté par les lignes de transport et non par les arrêts
  21    85 L''opérateur devrait être porté par les lignes de transport et non par les arrêts
  22    77 L''arrêt n''est desservi par aucune ligne (l''ajouter à une relation route)
  23    52 Les arrêts ne sont peut-être pas dans le bon ordre
  24    65 Une validation intransigeante des données de transport en commun
multi:
Status: Missing 0/0 - 24,0,0,0,0
```

**Comment by josmmirror** [comment]
> "Est-ce un arrêt de bus ? ajouter highway=bus_stop" is not supposed to be the label of a group and appears on tram stop without public_transport tag.

I get "Erreurs (1)
Il manque le tag public_transport sur un arrêt - Préciser s'il s'agit d'un arrêt (platform) ou d'un emplacement sur les rails (stop_position) (1)" for a sole railway=tram_stop node.

Asking again: Did you clear cache?

**Comment by stoecker** [comment]
>  "Est-ce un arrêt de bus ? ajouter highway=bus_stop" is not supposed to be the label of a group and appears on tram stop without public_transport tag.

I get "Erreurs (1)
Il manque le tag public_transport sur un arrêt - Préciser s'il s'agit d'un arrêt (platform) ou d'un emplacement sur les rails (stop_position) (1)" for a sole railway=tram_stop node.

Asking again: Did you clear cache?

**Comment by nlehuby** [comment]
nope. How can I clear the cache ?

**Comment by frodrigo** [comment]
@nlehuby remove the cache directory in your .josm

**Comment by stoecker** [comment]
Note that Klumbumbus disabled the rule, as the link is dead ATM.

**Comment by nlehuby** [comment]
This is ok for me too :tada: 
A big thanks to Fred, Pascal and Dirk for this long work :medal_military:

**Pull request merged**
