### PR TITLE
Check tags between route and route_master

### PR DESCRIPTION
**Pull request by nlehuby**
Add 3 tests:
- same operator between route and its line
- same network between route and its line
- same public transport mode between route and its line

### CODE REVIEW

**Comment by nlehuby** [comment]
Does somebody want to make a review ? Should I wait or should I merge ?

**Comment by frodrigo** [comment]
Untested. But for me it can't work.
```
relation.pt_route[tag(network)!=parent_tag(network)]
```
`parent_tag` and `tag` are on the object.

**Comment by nlehuby** [comment]
I don't understand your point :thinking: 

mapcss

**Comment by frodrigo** [comment]
- Parent selector https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation#Parentselector
- Eval expressions parent_tag https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation#Evalexpressions

**Comment by nlehuby** [comment]
Sorry but I still don't understand your remark: can you explicit what do you mean ?

**Pull request merged**
